// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1ug90KLmMZNx8y7RMcHezz-rIXz2KEFQ',
    appId: '1:264314484467:web:2f6f3b7a4caf10b613e986',
    messagingSenderId: '264314484467',
    projectId: 'buscodeproject',
    authDomain: 'buscodeproject.firebaseapp.com',
    storageBucket: 'buscodeproject.appspot.com',
    measurementId: 'G-J0921GLCQ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC1hWNbjlKNW4fXDk2g15a2MRo7xQ32ME',
    appId: '1:264314484467:android:9d7d8ac75313c67d13e986',
    messagingSenderId: '264314484467',
    projectId: 'buscodeproject',
    storageBucket: 'buscodeproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG7qJmSPm2G3KB3uQ_s3Fmg8pzhwaUBEU',
    appId: '1:264314484467:ios:865a77800ef7217913e986',
    messagingSenderId: '264314484467',
    projectId: 'buscodeproject',
    storageBucket: 'buscodeproject.appspot.com',
    iosClientId: '264314484467-djn70dol5mq0nbn6lj0boditokril3p0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
